name: run-mirror
on:
  workflow_dispatch:

jobs:
  run-mirror:
    if: github.repository == 'euxn23/blog-site-mirror'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          repositories: "blog-site-mirror"
      - uses: actions/checkout@v4
        with:
          repository: euxn23/blog-site
          token: ${{ steps.app-token.outputs.token }}
      - run: |
          git remote add mirror https://github.com/euxn23/blog-site-mirror.git
          git push mirror
